// SPDX-License-Identifier: MIT

'use client'

import * as React from 'react'

import { demos } from '@/components/demos'

type View = 'react' | 'html' | 'code'

/**
 * Live demo frame on generated component pages. Three views:
 *  - React: the real `@21stgov/commons-react` component (what the CLI installs).
 *  - HTML: the same component as framework-agnostic `.cui-*` markup, powered by
 *    `commons.css` + `commons-js`, isolated in an <iframe> (so that stylesheet's
 *    own reset/theme never collides with the docs' Tailwind). Served from
 *    /cui/<name>.html (generated by scripts/cui-frames.ts).
 *  - Code: the source snippet (when the MDX provides one).
 */
export function ComponentDemo({
  name,
  children,
}: {
  name: string
  children?: React.ReactNode
}): React.JSX.Element {
  const loader = demos[name]
  const Demo = React.useMemo(() => (loader ? React.lazy(loader) : undefined), [loader])
  const [view, setView] = React.useState<View>('react')
  const hasCode = React.Children.count(children) > 0

  // The HTML iframe is same-origin, so read its rendered height on load to size
  // the frame to its content instead of a scroll box.
  const iframeRef = React.useRef<HTMLIFrameElement>(null)
  const [htmlSeen, setHtmlSeen] = React.useState(false)
  const [frameHeight, setFrameHeight] = React.useState<number>()
  const [theme, setTheme] = React.useState('light')

  React.useEffect(() => {
    if (view !== 'html') return
    setHtmlSeen(true)
    setTheme(document.documentElement.classList.contains('dark') ? 'dark' : 'light')
  }, [view])

  const syncHeight = React.useCallback(() => {
    const body = iframeRef.current?.contentDocument?.body
    if (body) setFrameHeight(body.scrollHeight + 4)
  }, [])

  if (!Demo) {
    return (
      <p className="not-prose rounded-md border border-warning-border bg-warning p-4 text-warning-foreground">
        No live demo is registered for “{name}” yet.
      </p>
    )
  }

  return (
    <div className="docs-component-demo not-prose">
      <div role="group" aria-label="Example view" className="docs-component-demo-toolbar">
        <button type="button" aria-pressed={view === 'react'} onClick={() => setView('react')}>
          React
        </button>
        <button type="button" aria-pressed={view === 'html'} onClick={() => setView('html')}>
          HTML
        </button>
        {hasCode ? (
          <button type="button" aria-pressed={view === 'code'} onClick={() => setView('code')}>
            Code
          </button>
        ) : null}
      </div>

      <div className="docs-component-demo-preview" hidden={view !== 'react'}>
        <React.Suspense
          fallback={<p className="text-sm text-muted-foreground">Loading example…</p>}
        >
          <Demo />
        </React.Suspense>
      </div>

      <div className="docs-component-demo-html" hidden={view !== 'html'}>
        {htmlSeen ? (
          <iframe
            ref={iframeRef}
            src={`/cui/${name}.html?theme=${theme}`}
            title={`${name} — framework-agnostic HTML example`}
            className="docs-component-demo-frame"
            loading="lazy"
            onLoad={syncHeight}
            style={{ width: '100%', border: 0, height: frameHeight ?? 240 }}
          />
        ) : null}
      </div>

      {hasCode ? (
        <div className="docs-component-demo-code" hidden={view !== 'code'}>
          {children}
        </div>
      ) : null}
    </div>
  )
}
