// SPDX-License-Identifier: MIT

import type { ComponentType } from 'react'

export type DemoModule = { default: ComponentType }
export type DemoLoader = () => Promise<DemoModule>

/**
 * Registry-name → lazy live-demo module. Keeping each demo in its own chunk
 * prevents every component page from compiling the entire demo catalog.
 */
export const demos: Record<string, DemoLoader> = {
  accordion: () => import('./accordion.demo'),
  alert: () => import('./alert.demo'),
  'alert-dialog': () => import('./alert-dialog.demo'),
  'aspect-ratio': () => import('./aspect-ratio.demo'),
  avatar: () => import('./avatar.demo'),
  badge: () => import('./badge.demo'),
  breadcrumb: () => import('./breadcrumb.demo'),
  button: () => import('./button.demo'),
  'button-group': () => import('./button-group.demo'),
  calendar: () => import('./calendar.demo'),
  card: () => import('./card.demo'),
  carousel: () => import('./carousel.demo'),
  'character-count': () => import('./character-count.demo'),
  checkbox: () => import('./checkbox.demo'),
  'checkbox-group': () => import('./checkbox-group.demo'),
  collapsible: () => import('./collapsible.demo'),
  collection: () => import('./collection.demo'),
  'combo-box': () => import('./combo-box.demo'),
  'command-palette': () => import('./command-palette.demo'),
  'context-menu': () => import('./context-menu.demo'),
  'custom-select': () => import('./custom-select.demo'),
  'data-table': () => import('./data-table.demo'),
  'date-picker': () => import('./date-picker.demo'),
  'date-range-picker': () => import('./date-range-picker.demo'),
  dialog: () => import('./dialog.demo'),
  drawer: () => import('./drawer.demo'),
  'dropdown-menu': () => import('./dropdown-menu.demo'),
  'empty-state': () => import('./empty-state.demo'),
  field: () => import('./field.demo'),
  'file-input': () => import('./file-input.demo'),
  footer: () => import('./footer.demo'),
  form: () => import('./form.demo'),
  'gov-banner': () => import('./gov-banner.demo'),
  header: () => import('./header.demo'),
  'header-navigation-menu': () => import('./header-navigation-menu.demo'),
  'hover-card': () => import('./hover-card.demo'),
  icon: () => import('./icon.demo'),
  'icon-list': () => import('./icon-list.demo'),
  identifier: () => import('./identifier.demo'),
  'in-page-navigation': () => import('./in-page-navigation.demo'),
  input: () => import('./input.demo'),
  'input-group': () => import('./input-group.demo'),
  'input-mask': () => import('./input-mask.demo'),
  'input-otp': () => import('./input-otp.demo'),
  item: () => import('./item.demo'),
  kbd: () => import('./kbd.demo'),
  'language-selector': () => import('./language-selector.demo'),
  link: () => import('./link.demo'),
  list: () => import('./list.demo'),
  'memorable-date': () => import('./memorable-date.demo'),
  menubar: () => import('./menubar.demo'),
  meter: () => import('./meter.demo'),
  'navigation-menu': () => import('./navigation-menu.demo'),
  'number-field': () => import('./number-field.demo'),
  pagination: () => import('./pagination.demo'),
  popover: () => import('./popover.demo'),
  'process-list': () => import('./process-list.demo'),
  progress: () => import('./progress.demo'),
  prose: () => import('./prose.demo'),
  'radio-group': () => import('./radio-group.demo'),
  'resizable-panels': () => import('./resizable-panels.demo'),
  'scroll-area': () => import('./scroll-area.demo'),
  search: () => import('./search.demo'),
  select: () => import('./select.demo'),
  separator: () => import('./separator.demo'),
  sidebar: () => import('./sidebar.demo'),
  'site-alert': () => import('./site-alert.demo'),
  skeleton: () => import('./skeleton.demo'),
  slider: () => import('./slider.demo'),
  spinner: () => import('./spinner.demo'),
  'step-indicator': () => import('./step-indicator.demo'),
  'summary-box': () => import('./summary-box.demo'),
  table: () => import('./table.demo'),
  switch: () => import('./switch.demo'),
  tabs: () => import('./tabs.demo'),
  'time-picker': () => import('./time-picker.demo'),
  toast: () => import('./toast.demo'),
  toggle: () => import('./toggle.demo'),
  'toggle-group': () => import('./toggle-group.demo'),
  toolbar: () => import('./toolbar.demo'),
  tooltip: () => import('./tooltip.demo'),
  validation: () => import('./validation.demo'),
}
