// SPDX-License-Identifier: MIT

// @21stgov/commons-react — public API.

export { cn } from './lib/cn.js'

// RTL: Base UI components (dialog, tabs, accordion, menus, combobox…) read
// their reading direction from this provider, NOT the DOM `dir` attribute —
// without it they default to LTR even under `<html dir="rtl">`. Wrap your app
// once in `<DirectionProvider direction="rtl">`. Native components (link,
// breadcrumb, etc.) flip from the DOM `dir` on their own.
export {
  DirectionProvider,
  useDirection,
  type TextDirection,
} from '@base-ui/react/direction-provider'

// components
// Component agents: append your own `export * from "@/components/<name>";`
// line below (keep the list alphabetized).
export * from '@/components/accordion'
export * from '@/components/alert'
export * from '@/components/alert-dialog'
export * from '@/components/aspect-ratio'
export * from '@/components/avatar'
export * from '@/components/badge'
export * from '@/components/breadcrumb'
export * from '@/components/button'
export * from '@/components/button-group'
export * from '@/components/calendar'
export * from '@/components/card'
export * from '@/components/carousel'
export * from '@/components/character-count'
export * from '@/components/checkbox'
export * from '@/components/checkbox-group'
export * from '@/components/collapsible'
export * from '@/components/collection'
export * from '@/components/combo-box'
export * from '@/components/command-palette'
export * from '@/components/context-menu'
export * from '@/components/custom-select'
export * from '@/components/data-table'
export * from '@/components/date-picker'
export * from '@/components/date-range-picker'
export * from '@/components/dialog'
export * from '@/components/drawer'
export * from '@/components/dropdown-menu'
export * from '@/components/empty-state'
export * from '@/components/field'
export * from '@/components/field/context'
export * from '@/components/file-input'
export * from '@/components/footer'
export * from '@/components/form'
export * from '@/components/gov-banner'
export * from '@/components/header'
export * from '@/components/hover-card'
export * from '@/components/icon'
export * from '@/components/icon-list'
export * from '@/components/identifier'
export * from '@/components/in-page-navigation'
export * from '@/components/input'
export * from '@/components/input-group'
export * from '@/components/input-mask'
export * from '@/components/input-otp'
export * from '@/components/item'
export * from '@/components/kbd'
export * from '@/components/language-selector'
export * from '@/components/link'
export * from '@/components/list'
export * from '@/components/memorable-date'
export * from '@/components/menubar'
export * from '@/components/meter'
export * from '@/components/navigation-menu'
export * from '@/components/number-field'
export * from '@/components/pagination'
export * from '@/components/popover'
export * from '@/components/process-list'
export * from '@/components/progress'
export * from '@/components/prose'
export * from '@/components/radio-group'
export * from '@/components/resizable-panels'
export * from '@/components/scroll-area'
export * from '@/components/search'
export * from '@/components/select'
export * from '@/components/separator'
export * from '@/components/sidebar'
export * from '@/components/site-alert'
export * from '@/components/skeleton'
export * from '@/components/slider'
export * from '@/components/spinner'
export * from '@/components/step-indicator'
export * from '@/components/summary-box'
export * from '@/components/switch'
export * from '@/components/table'
export * from '@/components/tabs'
export * from '@/components/time-picker'
export * from '@/components/toast'
export * from '@/components/toggle'
export * from '@/components/toggle-group'
export * from '@/components/toolbar'
export * from '@/components/tooltip'
export * from '@/components/validation'
